language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm install
  - npm test
  - npm run build
  - npx semantic-release
addons:
  sonarcloud:
    organization: "nicksont-github"
    token:
      secure: SONAR_TOKEN

