---
jobs:
  release:
    docker:
      -
        image: "circleci/node:8"
    steps:
      - checkout
      -
        run: "npm install"
      -
        run: "npm build"
      -
        run: "npx semantic-release"
  test:
    docker:
      -
        image: "circleci/node:8"
    steps:
      - checkout
      -
        run: "npm install"
      -
        run: "npm test"
version: 2

