jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm test
  release:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm build
      - run: npx semantic-release

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - release:
          requires:
            - test

