version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm test
  release:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm build
      - run: npx semantic-release

workflows:
  version: 2
  continuous_deploy:
    jobs:
      - test
      - release

